### ISSUE TITLE
FasterRCNN: 'ReidRoIHead is not in the models registry

### ISSUE THREAD

**Issue by Wenfeng6** [ljpadam/CGPS#1]
Could you please help me with this bug?

Traceback (most recent call last):
  File "../../tools/train.py", line 177, in <module>
    main()
  File "../../tools/train.py", line 151, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/home/lwf/wsps/mmdetection-master/mmdet/models/builder.py", line 58, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/lwf/wsps/mmcv/mmcv/utils/registry.py", line 210, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/lwf/wsps/mmcv/mmcv/cnn/builder.py", line 26, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/lwf/wsps/mmcv/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "FasterRCNN: 'ReidRoIHead is not in the models registry'"

**Comment by Wenfeng6** [comment]
or could you tell me your cuda version and python version?

**Comment by Wenfeng6** [comment]
when I change the vesion of mmcv=1.2.6 as you set, I got this bug:
Traceback (most recent call last):
  File "../../tools/train.py", line 14, in <module>
    from mmdet import __version__
  File "/home/lwf/wsps/mmdetection/mmdet/__init__.py", line 25, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.2.6 is used but incompatible. Please install mmcv>=1.3.8, <=1.4.0.

**Comment by Wenfeng6** [comment]
When I use the MMCV=1.3.9, I got the bug:KeyError: "FasterRCNN: 'ReidRoIHead is not in the models registry'"
Please help me, thank you very much!

**Comment by Wenfeng6** [comment]
I find that I can download the older version MMdetection to solve the problem, could you please tell me the MMdetection you are using?

**Comment by Wenfeng6** [comment]
I have solved the problem by myself, thanks

**Comment by sysuchx** [comment]
I also encountered this problem. How did you solve it? Thanks

**Comment by shijie2458** [comment]
> I also encountered this problem. How did you solve it? Thanks
